[env]
PYTHON_DIR = "src/main/python"

[config]
default_to_workspace = false

[tasks.generate-resources]
script_runner = "@shell"
script = '''
pyside2-rcc resources/console_resources.qrc -o src/main/python/console_resources.py
'''

[tasks.copy-capnp]
script_runner = "@shell"
script = '''
cp src/main/resources/base/console_backend.capnp console_backend/console_backend.capnp
'''

[tasks.run]
dependencies = ["copy-capnp", "generate-resources"]
script = '''
pip install -e ./console_backend
fbs run
'''

[tasks.run-prod]
dependencies = ["copy-capnp", "generate-resources"]
script = '''
pip install --force ./console_backend
fbs run
'''

[tasks.prod-installer]
dependencies = ["copy-capnp", "generate-resources"]
script = '''
pip install --force ./console_backend
fbs freeze
fbs installer
'''

[tasks.rust-fmt]
dependencies = ["copy-capnp"]
command = "cargo"
args    = ["fmt", "--", "--check"]

[tasks.rust-clippy]
dependencies = ["copy-capnp"]
command = "cargo"
args    = ["clippy", "--all-targets", "--", "--deny", "warnings"]

[tasks.rust-tests]
dependencies = ["copy-capnp"]
command = "cargo"
args    = ["test", "--", "--nocapture"]

[tasks.python-type-check]
command = "mypy"
args    = ["${PYTHON_DIR}"]

[tasks.python-format-check]
command = "black"
args    = ["--line-length=120", "--check", "--diff", "${PYTHON_DIR}"]

[tasks.python-format-all]
command = "black"
args    = ["--line-length=120", "${PYTHON_DIR}"]

[tasks.python-format]
alias="python-format-all"

[tasks.python-lint]
command = "pylint"
args    = ["--output-format=parseable", "${PYTHON_DIR}"]
