env_scripts = [
  '''
#!@duckscript
# set os specific env vars
os = os_family
if eq ${os} windows
  set_env STANDALONE_PY_URL "${STANDALONE_PY_BASE_URL}/cpython-3.9.7-x86_64-pc-windows-msvc-shared-pgo-20211017T1616.tar.zst"
  set_env PYTHON "${WORKSPACE}\\py39\\python.exe"
  set_env DIST_PYTHON "${WORKSPACE}\\py39-dist\\python"
  set_env PYSIDE2_RCC "${WORKSPACE}\\py39\\Lib\\site-packages\\PySide2\\rcc.exe"
  set_env BACKEND_WHEEL console_backend-0.1.0-cp39-cp39-win_amd64.whl
  set_env BUILD_TRIPLET "x86_64-pc-windows-msvc"
  set_env PYO3_CONFIG_FILE "${WORKSPACE}\\standalone-py\\pyo3_config.txt"
elseif eq ${os} linux
  set_env STANDALONE_PY_URL "${STANDALONE_PY_BASE_URL}/cpython-3.9.7-x86_64-unknown-linux-gnu-lto-20211017T1616.tar.zst"
  set_env PYTHON "${WORKSPACE}/py39/bin/python3"
  set_env DIST_PYTHON "${WORKSPACE}/py39-dist/bin/python3"
  set_env PYSIDE2_RCC "${WORKSPACE}/py39/bin/pyside2-rcc"
  set_env BACKEND_WHEEL console_backend-0.1.0-cp39-cp39-linux_x86_64.whl
  set_env PYO3_CONFIG_FILE "${WORKSPACE}/standalone-py/pyo3_config.txt"
  output = exec --fail-on-error gcc -dumpmachine
  triplet = trim ${output.stdout}
  set_env BUILD_TRIPLET ${triplet}
else
  set_env STANDALONE_PY_URL "${STANDALONE_PY_BASE_URL}/cpython-3.9.7-x86_64-apple-darwin-lto-20211017T1616.tar.zst"
  set_env PYTHON "${WORKSPACE}/py39/bin/python3"
  set_env DIST_PYTHON "${WORKSPACE}/py39-dist/bin/python3"
  set_env PYSIDE2_RCC "${WORKSPACE}/py39/bin/pyside2-rcc"
  set_env BACKEND_WHEEL console_backend-0.1.0-cp39-cp39-macosx_10_15_x86_64.whl
  set_env PYO3_CONFIG_FILE "${WORKSPACE}/standalone-py/pyo3_config.txt"
  output = exec --fail-on-error gcc -dumpmachine
  triplet = trim ${output.stdout}
  set_env BUILD_TRIPLET ${triplet}
end
''',
]

[config]
default_to_workspace = false
init_task = "init"
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[env]
WORKSPACE = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
STANDALONE_PY_BASE_URL = "https://github.com/indygreg/python-build-standalone/releases/download/20211017"
MACOSX_DEPLOYMENT_TARGET = "10.15"

[tasks.init]

# Two proposed methods of simplifying path globbing # https://github.com/sagiegurari/cargo-make/issues/542 # https://github.com/sagiegurari/cargo-make/issues/543
[tasks.set-qml-files]
private = true
condition = { env_not_set = ["QML_FILES"] }
script_runner = "@duckscript"
script = '''
!include_files ./utils/glob.ds
qml_files = glob_paths_excluding_target resources/**/*.qml
set_env QML_FILES ${qml_files}
'''

[tasks.set-qml-app]
private = true
condition = { env_not_set = ["QT_APP"] }
script_runner = "@duckscript"
script = '''
python = get_env PYTHON
output = exec ${python} utils/echo-qt-dir.py
qt_app = trim ${output.stdout}
set_env QT_APP ${qt_app}
'''

[tasks.set-python-files]
private = true
condition = { env_not_set = ["PYTHON_FILES"] }
script_runner = "@duckscript"
script = '''
!include_files ./utils/glob.ds
py_files = glob_paths_excluding_target ./**/*.py
set_env PYTHON_FILES ${py_files}
'''

[tasks.rustup-update]
command = "rustup"
args = ["update", "stable"]

[tasks.cargo-make-deps-update]
dependencies = ["rustup-update"]
install_crate = { crate_name = "cargo-update", binary = "cargo-install-update", test_arg = [
  "-V",
], min_version = "7.0.1" }
command = "cargo"
args = ["install-update", "taplo-cli", "cargo-make"]

[tasks.generate-common-constants-rs]
script_runner = "@duckscript"
script = '''
python = get_env PYTHON
exec ${python} -m py2many --rust=1 swiftnav_console/constants.py
mv swiftnav_console/constants.rs console_backend/src/common_constants.rs
'''

[tasks.extract-piksi-constants-rs]
script_runner = "@duckscript"
script = '''
python = get_env PYTHON
output = exec --fail-on-error ${python} utils/extract_piksi_tools_constants.py
writefile /tmp/piksi_tools_constants.py ${output.stdout}
exec --fail-on-error ${python} -m py2many --rust=1 /tmp/piksi_tools_constants.py --outdir console_backend/src/
'''

[tasks.generate-resources]
command = "${PYSIDE2_RCC}"
args = [
  "resources/console_resources.qrc",
  "-o",
  "swiftnav_console/console_resources.py",
  "-g",
  "python",
]

[tasks.check-capnp]
script_runner = "@shell"
script = '''
capnp compile -oc++ src/main/resources/base/console_backend.capnp
rm src/main/resources/base/console_backend.capnp.c++
rm src/main/resources/base/console_backend.capnp.h
'''

[tasks.copy-capnp]
dependencies = ["check-capnp"]
script_runner = "@shell"
script = '''
cp src/main/resources/base/console_backend.capnp console_backend/console_backend.capnp
'''

[tasks.remove-egg-dist]
script_runner = "@shell"
script = '''
rm -rf console_backend/*.dist-info
rm -rf console_backend/*.egg-info
'''

[tasks.remove-egg-dist.windows]
script_runner = "powershell"
script_extension = "ps1"
script = '''
Get-ChildItem .\console_backend -Recurse -Include @("*.egg-info", "*.dist-info") | Remove-Item -Force -Recurse
'''

[tasks.start-console]
command = "${PYTHON}"
args = ["-m", "swiftnav_console.main", "${@}"]

[tasks.start-console-gdb]
command = "rust-gdb"
args = [
  "-ex",
  "run",
  "--args",
  "${PYTHON}",
  "-m",
  "swiftnav_console.main",
  "${@}",
]

[tasks.qml-run]
dependencies = ["generate-resources"]
run_task = "start-console"

[tasks.run]
dependencies = [
  "copy-capnp",
  "generate-resources",
  "remove-egg-dist",
  "store-version",
  "install-backend",
]
run_task = "start-console"

[tasks.gdb-run]
dependencies = [
  "copy-capnp",
  "generate-resources",
  "remove-egg-dist",
  "store-version",
  "install-backend",
]
run_task = "start-console-gdb"

[tasks.prod-run]
dependencies = [
  "copy-capnp",
  "generate-resources",
  "remove-egg-dist",
  "store-version",
  "prod-install-backend",
]
run_task = "start-console"

[tasks.headless-run]
command = "cargo"
args = [
  "run",
  "--bin",
  "headless-console",
  "--release",
  "--no-default-features",
  "${@}",
]

[tasks.store-version]
script_runner = "@shell"
script = '''
git describe --tags --always > console_backend/src/version.txt
'''

[tasks.install-backend]
command = "${PYTHON}"
args = ["-m", "pip", "install", "-e", "./console_backend"]

[tasks.prod-install-backend]
command = "${PYTHON}"
args = [
  "-m",
  "pip",
  "install",
  "-v",
  "--upgrade",
  "--force",
  "./console_backend",
]

[tasks.build-frontend-wheel]
command = "${PYTHON}"
args = ["-m", "flit", "build", "--no-setup-py"]

[tasks.build-backend-wheel]
cwd = "console_backend"
command = "${PYTHON}"
args = ["setup.py", "bdist_wheel"]

[tasks.get-get-pip]
script_runner = "@duckscript"
script = '''
wget -O ./get-pip.py https://bootstrap.pypa.io/get-pip.py
'''

[tasks.write-pyo3-config]
script_runner = "@duckscript"
cwd = "standalone-py"
condition = { files_not_exist = ["${PYO3_CONFIG_FILE}"] }
script = '''
writefile pyo3_config.txt "implementation=CPython\nversion=3.9\nshared=true\nabi3=false\nlib_name=python3.9\nlib_dir=${WORKSPACE}/standalone-py/python/install/lib\nexecutable=${WORKSPACE}/standalone-py/python/install/bin/python3.9\npointer_width=64\nbuild_flags=WITH_THREAD\nsuppress_build_script_link_lines=false\n"
'''

[tasks.write-pyo3-config.windows]
script_runner = "@duckscript"
cwd = "standalone-py"
condition = { files_not_exist = ["${PYO3_CONFIG_FILE}"] }
script = '''
writefile pyo3_config.txt "implementation=CPython\nversion=3.9\nshared=true\nabi3=false\nlib_name=python39\nlib_dir=${WORKSPACE}\\standalone-py\\python\\install\\libs\nexecutable=${WORKSPACE}\\standalone-py\\python\\install\\python.exe\npointer_width=64\nbuild_flags=WITH_THREAD\nsuppress_build_script_link_lines=false\n"
'''

[tasks.get-standalone-py]
dependencies = ["get-get-pip", "write-pyo3-config"]
cwd = "standalone-py"
condition = { files_not_exist = ["${WORKSPACE}/standalone-py/python"] }
script_runner = "@duckscript"
script = '''
wget -O py39.tar.zst ${STANDALONE_PY_URL}
exec --fail-on-error zstd -f -d py39.tar.zst
exec --fail-on-error tar -xvf py39.tar
'''

[tasks.setup-builder]
dependencies = ["get-standalone-py"]
script_runner = "@duckscript"
script = '''
if is_path_exists py39
  rm -r py39
end
mkdir py39
cd standalone-py/python/install
cp . ../../../py39
cd ../../../
exec --fail-on-error ${PYTHON} ./get-pip.py
exec --fail-on-error ${PYTHON} -m pip install wheel flit . ".[test]"
cm_run_task generate-resources
'''

[tasks.prep-dist]
script_runner = "@duckscript"
script = '''
cm_run_task copy-capnp
cm_run_task store-version
if is_path_exists py39-dist
  rm -r py39-dist
end
mkdir py39-dist
cd standalone-py/python/install/
cp . ../../../py39-dist
cd ../../..
exec --fail-on-error ${DIST_PYTHON} ./get-pip.py
'''

[tasks.build-console]
command = "cargo"
args = ["build", "--release", "-vv", "--bin", "console"]

[tasks.build-dist-install-console]
dependencies = ["build-console"]
script_runner = "@duckscript"
script = '''
cp target/release/console py39-dist/console
os = os_family
if eq ${os} mac
  exec --fail-on-error install_name_tool -change /install/lib/libpython3.9.dylib @executable_path/lib/libpython3.9.dylib py39-dist/console
end
'''

[tasks.build-dist-install-console.windows]
script = '''
cp target/release/console.exe py39-dist/console.exe
cp target/release/console.pdb py39-dist/console.pdb
cp target/x86_64-pc-windows-msvc/release/console_backend.pdb py39-dist/Lib/site-packages/console_backend/console_backend.pdb
'''

[tasks.build-dist-install-frontend-wheel]
dependencies = ["build-frontend-wheel"]
command = "${DIST_PYTHON}"
args = [
  "-m",
  "pip",
  "install",
  "./dist/swiftnav_console-0.1.0-py3-none-any.whl",
  "--force-reinstall",
]

[tasks.build-dist-install-backend-wheel]
dependencies = ["build-backend-wheel"]
command = "${DIST_PYTHON}"
args = ["-m", "pip", "install", "console_backend/dist/${BACKEND_WHEEL}"]

[tasks.build-dist-copy-resources]
script_runner = "@duckscript"
script = '''
cp src/main/resources py39-dist/
'''

[tasks.build-dist-freeze]
script_runner = "@duckscript"
script = '''
touch ./py39-dist/.frozen
'''

[tasks.build-dist]
dependencies = ["prep-dist"]
run_task = [
  { name = [
    "build-dist-install-frontend-wheel",
    "build-dist-install-backend-wheel",
    "build-dist-install-console",
    "build-dist-copy-resources",
    "build-dist-freeze",
  ] },
]

[tasks.purge-dist]
env = { PYTHONDONTWRITEBYTECODE = "1" }
cwd = "py39-dist"
script_runner = "@duckscript"
script = '''
py_folders = array test tests examples __pycache__ demos turtledemo translations idlelib lib/tcl8 lib/tcl8.6 lib/tk8.6 shiboken2/docs ensurepip lib2to3 tkinter unittest include
qt_folders = array plugins/geoservices plugins/virtualkeyboard plugins/sqldrivers lib/Tix8.4.3 tcl/tix8.4.3 Qt/resources PySide2/resources
qml_folders = array qml/QtWeb* qml/QtBluetooth* qml/QtNfc* qml/QtGamepad qml/QtTest qml/QtQuick3D qml/Qt3D qml/QtSensors qml/QtLocation qml/QtPositioning
all_folders = array_concat ${py_folders} ${qt_folders} ${qml_folders}
for name in ${all_folders}
    folders = glob_array **/${name}/
    for folder in ${folders}
        rm -r ${folder}
    end
end

file_exts = array pyc pyi tcl gif png
for ext in ${file_exts}
    files = glob_array **/*.${ext}
    for file in ${files}
        if eq ${ext} png
            is_qtquick = contains ${file} QtQuick
            if not is_qtquick
                rm ${file}
            end
        else
            rm ${file}
        end
    end
end

libs = array QtSensors QtLocation Qt5Location QtPositioning Qt3D Qt53D Qt5Nfc Qt5Web QtWeb Qt5Pdf Qt5Designer Qt5DesignerComponents Qt5VirtualKeyboard Qt5Bluetooth Qt5Quick3D
for lib in ${libs}
    files = glob_array ./**/*${lib}*
    for file in ${files}
        echo ${file}
        rm -r ${file}
    end
end

os = os_family
if eq ${os} windows
    rm -r ./Scripts

    rm -r ./include
    rm -r ./tcl

    globs = array _test*.pyd libcrypto*.dll libssl*.dll tcl*.dll tk*.dll
    for glob in ${globs}
        files = glob_array ./DLLs/${glob}
        for file in ${files}
            rm ${file}
        end
    end
    qtbins = glob_array ./Lib/site-packages/PySide2/*.exe
    for bin in ${qtbins}
        rm ${bin}
    end
else
    rm -r ./share

    bins = array rcc uic designer
    for bin in ${bins}
        files = glob_array ./**/PySide2/${bin}
        for bin in ${files}
            rm ${bin}
        end
    end
end

exec --fail-on-error ${DIST_PYTHON} -m pip uninstall -y pip setuptools wheel flit
exec --fail-on-error ${DIST_PYTHON} -m compileall -b -f -o 1 -o 2 .

if eq ${os} windows
    globs = array pyexpat.* sqlite3.* _ctypes_test.* _bz2.* _decimal.* _elementtree.* _multiprocessing.* _sqlite3.* _ssl.* _tkinter.* _uuid.* _zoneinfo.* _msi.* _test*.*
    for glob in ${globs}
        files = glob_array ./DLLs/${glob}
        for file in ${files}
            rm ${file}
        end
        files = glob_array ./libs/${glob}
        for file in ${files}
            rm ${file}
        end
    end
else
    globs = array *.a
    for glob in ${globs}
        files = glob_array ./lib/**/${glob}
        for file in ${files}
            rm ${file}
        end
    end
endif

py_internal_libs = array Lib/email Lib/distutils Lib/http Lib/multiprocessing Lib/msilib Lib/http Lib/dbm Lib/curses Lib/xml Lib/xmlrpc Lib/urllib Lib/ensurepip Lib/venv Lib/wsgiref Lib/lib2to3

for name in ${py_internal_libs}
    folders = glob_array **/${name}/
    for folder in ${folders}
        rm -r ${folder}
    end
end

files = glob_array ./**/*.py
for file in ${files}
    rm ${file}
end
'''

[tasks.strip-dist-pdb.windows]
cwd = "py39-dist"
script_runner = "@duckscript"
script = '''
files = glob_array **/*.pdb
for file in ${files}
    echo "Removing ${file}..."
    rm -f ${file}
end
'''

[tasks.strip-dist]
script_runner = "@duckscript"
script = '''
exec --fail-on-error strip ./py39-dist/console
rm -r ./py39-dist/bin
'''

[tasks.strip-dist.windows]
script_runner = "@duckscript"
script = '''
cm_run_task strip-dist-pdb
exec --fail-on-error strip.exe ./py39-dist/console.exe
rm ./py39-dist/python.exe
rm ./py39-dist/pythonw.exe
'''

[tasks.compress-dist]
env = { ARCHIVE_NAME = "console_pp" }
script_runner = "@duckscript"
script = '''
output = exec --fail-on-error date +%Y-%m-%d
date = trim ${output.stdout}
output = exec --fail-on-error git describe --always --tags --dirty
version = trim ${output.stdout}
output_name = set "${ARCHIVE_NAME}-${version}-${BUILD_TRIPLET}-${date}"
exec --fail-on-error tar -C "py39-dist" -cvf "${output_name}-debug.tar" .
cm_run_task strip-dist
exec --fail-on-error tar -C "py39-dist" -cvf "${output_name}.tar" .
exec --fail-on-error rm -f "${output_name}.tar.xz"
exec --fail-on-error xz -T 0 -e -9 "${output_name}-debug.tar"
exec --fail-on-error xz -T 0 -e -9 "${output_name}.tar"
'''

[tasks.create-dist]
run_task = [{ name = ["build-dist", "purge-dist", "compress-dist"] }]

[tasks.dist-to-installer]

[tasks.dist-to-installer.windows]
script_runner = "@shell"
script = '''
makensis /V4  .\installers\Windows\Installer.nsi
'''

[tasks.qml-format]
dependencies = ["set-qml-files", "set-qml-app"]
script_runner = "@shell"
script = '''
${QT_APP}/Qt/bin/qmlformat -i ${QML_FILES}
'''

[tasks.qml-format.windows]
dependencies = ["set-qml-files", "set-qml-app"]
script_runner = "powershell"
script_extension = "ps1"
script = '''
& ${env:QT_APP}\Qt\bin\qmlformat -i $(-split ${env:QML_FILES})
'''

[tasks.qml-lint]
dependencies = ["set-qml-files", "set-qml-app"]
script_runner = "@shell"
script = '''
${QT_APP}/Qt/bin/qmllint -I ${QT_APP}/../PySide2/Qt/qml/ -I resources/ ${QML_FILES}
'''

[tasks.qml-lint.windows]
dependencies = ["set-qml-files", "set-qml-app"]
script_runner = "powershell"
script_extension = "ps1"
script = '''
& ${env:QT_APP}\Qt\bin\qmllint -I ${env:QT_APP}\..\PySide2\Qt\qml -I resources $(-split ${env:QML_FILES})
'''

[tasks.qml-format-check]
dependencies = ["qml-format"]
run_task = "check-git-diff"

[tasks.rust-format]
dependencies = ["copy-capnp"]
command = "cargo"
args = ["fmt", "--all"]

[tasks.rust-format-check]
dependencies = ["copy-capnp"]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.rust-lint]
dependencies = ["store-version", "copy-capnp"]
command = "cargo"
args = ["clippy", "--all-targets", "--", "--deny", "warnings"]

[tasks.rust-tests]
dependencies = ["store-version", "copy-capnp"]
command = "cargo"
cwd = "console_backend"
args = ["test", "--features", "tests", "${@}", "--", "--nocapture"]

[tasks.rust-type-check]
dependencies = ["store-version", "copy-capnp"]
command = "cargo"
args = ["check"]

[tasks.python-type-check]
dependencies = ["set-python-files"]
command = "${PYTHON}"
args = ["-m", "mypy", "@@split(PYTHON_FILES, )"]

[tasks.python-format-check]
dependencies = ["set-python-files"]
command = "${PYTHON}"
args = ["-m", "black", "--check", "--diff", "@@split(PYTHON_FILES, )"]

[tasks.python-format-all]
dependencies = ["set-python-files"]
command = "${PYTHON}"
args = ["-m", "black", "@@split(PYTHON_FILES, )"]

[tasks.python-format]
alias = "python-format-all"

[tasks.python-lint]
dependencies = ["set-python-files"]
command = "${PYTHON}"
args = ["-m", "pylint", "--output-format=parseable", "@@split(PYTHON_FILES, )"]

[tasks.toml-format-check]
# Note format-toml task is defined by cargo-make to use crate taplo-cli, but the version is
# unspecified.  Task cargo-make-deps-update keeps the dev version in sync with CI.
# https://github.com/sagiegurari/cargo-make/issues/571
dependencies = ["cargo-make-deps-update", "format-toml"]
run_task = "check-git-diff"

[tasks.format-all]
run_task = [
  { name = [
    "python-format-all",
    "qml-format",
    "rust-format",
    "newline-format",
    "format-toml",
  ] },
]

[tasks.format]
alias = "format-all"

[tasks.format-check]
dependencies = [
  "python-format-check",
  "rust-format-check",
  "newline-check",
  "qml-format-check",
  "toml-format-check",
]
run_task = "check-git-diff"

[tasks.lint]
dependencies = ["qml-lint", "python-lint", "rust-lint", "format-check"]

[tasks.types]
dependencies = ["python-type-check", "rust-type-check"]

[tasks.check-all]
dependencies = [
  "cargo-make-deps-update",
  "generate-common-constants-rs",
  "extract-piksi-constants-rs",
  "format",
  "lint",
  "types",
]
run_task = "check-git-diff"

[tasks.tests]
dependencies = ["rust-tests"]

# Create 'test' alias
[tasks.test]
clear = true
run_task = "tests"

[tasks.backend-cpu-bench]
dependencies = ["copy-capnp", "generate-resources"]
command = "cargo"
args = ["bench", "--all-features", "--", "--verbose", "--noplot"]

[tasks.backend-cpu-bench-validate]
command = "${PYTHON}"
args = ["utils/bench_runner.py", "--backend_cpu"]

[tasks.backend-mem-bench]
dependencies = ["copy-capnp", "generate-resources"]
command = "cargo"
args = [
  "test",
  "test_run_process_messages",
  "--manifest-path=console_backend/Cargo.toml",
  "--features",
  "benches",
  "--",
  "--nocapture",
]

[tasks.backend-benches]
dependencies = [
  "store-version",
  "backend-cpu-bench",
  "backend-cpu-bench-validate",
  "backend-mem-bench",
]

[tasks.disk-usage-bench]
command = "${PYTHON}"
args = ["utils/bench_runner.py", "--disk_usage"]

[tasks.frontend-cpu-bench.linux]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_cpu --executable=${WORKSPACE}/py39-dist/console
'''

[tasks.frontend-cpu-bench.windows]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_cpu --executable=${WORKSPACE}/py39-dist/console.exe
'''

[tasks.frontend-cpu-bench.mac]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_cpu --executable=${WORKSPACE}/py39-dist/console
'''

[tasks.frontend-mem-bench.linux]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_mem --executable=${WORKSPACE}/py39-dist/console
'''

[tasks.frontend-mem-bench.windows]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_mem --executable=${WORKSPACE}/py39-dist/console.exe
'''

[tasks.frontend-mem-bench.mac]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_mem --executable=${WORKSPACE}/py39-dist/console
'''

[tasks.newline-terminator]
private = true
script_runner = "python"
script_extension = "py"
script = '''
import os
import sys
import subprocess
def raises_exc(func):
    try: func()
    except: return True
    return False
dry_run = os.environ.get("NLT_DRY_RUN", "") == "1"
open_append = lambda fn: open(fn, "ta")
open_read = lambda fn: open(fn, "rb")
seek_end = lambda fp: (fp.seek(-1, 2), fp)[-1]
has_newline = lambda fn: seek_end(open_read(fn)).read(1) == b"\n"
append_newline = lambda fn: (open_append(fn).write("\n") if not dry_run else None, fn)[-1]
try_open_text = lambda fn: lambda: (open(fn, "ta"), open(fn, "tr").read(4096))
valid_file = lambda fn: os.path.getsize(fn) > 0 and not raises_exc(try_open_text(fn))
no_trailing_lf = lambda fn: valid_file(fn) and not has_newline(fn)
all_files = subprocess.check_output(["git", "ls-files"]).decode('utf8').splitlines()
no_newline = list(map(append_newline, filter(no_trailing_lf, all_files)))
footer = "*********************************************\n"
err = "ERROR: " if dry_run else "Fixing "
header = footer + "*** " + err + "files missing trailing newline ***\n" + footer
sys.stderr.write(header + str.join("\n", no_newline) + "\n" + footer) \
  if no_newline else None
sys.exit(int(len(no_newline) > 0) if dry_run else 0)
'''

[tasks.newline-check]
env = { NLT_DRY_RUN = "1" }
run_task = "newline-terminator"

[tasks.newline-format]
run_task = "newline-terminator"

[tasks.check-git-diff]
command = "git"
args = ["diff", "--exit-code"]
