env_scripts = [
  '''
#!@duckscript
!include_files ./utils/glob.ds

py_files = glob_paths_excluding_target ./**/*.py

set_env PYTHON_FILES ${py_files}
echo PYTHON_FILES=${py_files}

qml_files = glob_paths_excluding_target resources/**/*.qml

set_env QML_FILES ${qml_files}
echo QML_FILES=${qml_files}
''',
] # Two proposed methods of simplifying path globbing # https://github.com/sagiegurari/cargo-make/issues/542 # https://github.com/sagiegurari/cargo-make/issues/543

[env]
CONDA_ENV = "console_pp"
REQUIREMENTS_FILE = "requirements.txt"
REQUIREMENTS_DEV_FILE = "requirements-dev.txt"

[config]
default_to_workspace = false
init_task = "init"

[tasks.init]

[tasks.rustup-update]
command = "rustup"
args = ["update", "stable"]

[tasks.cargo-make-deps-update]
dependencies = ["rustup-update"]
install_crate = { crate_name = "cargo-update", binary = "cargo-install-update", test_arg = [
  "-V",
], min_version = "7.0.1" }
command = "cargo"
args = ["install-update", "taplo-cli", "cargo-make"]

# Create 'test' alias
[tasks.test]
clear = true
run_task = "tests"

[tasks.poetry-export-dev]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV poetry export --dev -f $REQUIREMENTS_FILE --output $REQUIREMENTS_DEV_FILE --without-hashes
'''

[tasks.poetry-export]
dependencies = ["poetry-export-dev"]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV poetry export -f $REQUIREMENTS_FILE --output $REQUIREMENTS_FILE --without-hashes
'''

[tasks.pip-install-dev]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pip install -r $REQUIREMENTS_DEV_FILE
'''

[tasks.pip-install]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pip install -r $REQUIREMENTS_FILE
'''

[tasks.generate-common-constants-rs]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV --no-capture-output --live-stream py2many --rust=1 src/main/python/constants.py
mv src/main/python/constants.rs console_backend/src/common_constants.rs
'''

[tasks.extract-piksi-constants-rs]
dependencies = ["pip-install-dev"]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV --no-capture-output --live-stream python utils/extract_piksi_tools_constants.py > /tmp/piksi_tools_constants.py
conda run -n $CONDA_ENV --no-capture-output --live-stream python -m py2many --rust=1 /tmp/piksi_tools_constants.py --outdir console_backend/src/
'''

[tasks.generate-resources]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV --no-capture-output --live-stream pyside2-rcc resources/console_resources.qrc -o src/main/python/console_resources.py
'''

[tasks.check-capnp]
script_runner = "@shell"
script = '''
capnp compile -oc++ src/main/resources/base/console_backend.capnp
rm src/main/resources/base/console_backend.capnp.c++
rm src/main/resources/base/console_backend.capnp.h
'''

[tasks.copy-capnp]
dependencies = ["check-capnp"]
script_runner = "@shell"
script = '''
cp src/main/resources/base/console_backend.capnp console_backend/console_backend.capnp
'''

[tasks.remove-egg-dist]
script_runner = "@shell"
script = '''
rm -rf console_backend/*.dist-info
rm -rf console_backend/*.egg-info
'''

[tasks.remove-egg-dist.windows]
script_runner = "powershell"
script_extension = "ps1"
script = '''
Get-ChildItem .\console_backend -Recurse -Include @("*.egg-info", "*.dist-info") | Remove-Item -Force -Recurse
'''

[tasks.start-console]
command = "conda"
args = [
  "run",
  "-n",
  "${CONDA_ENV}",
  "--no-capture-output",
  "--live-stream",
  "python",
  "src/main/python/main.py",
  "${@}",
]

[tasks.run]
dependencies = [
  "copy-capnp",
  "generate-resources",
  "remove-egg-dist",
  "store-version",
  "install-backend",
]
run_task = "start-console"

[tasks.prod-run]
dependencies = [
  "copy-capnp",
  "generate-resources",
  "remove-egg-dist",
  "store-version",
  "prod-install-backend",
]
run_task = "start-console"

[tasks.headless-run]
command = "cargo"
args = [
  "run",
  "--bin",
  "headless-console",
  "--release",
  "--no-default-features",
  "${@}",
]

[tasks.store-version]
script_runner = "@shell"
script = '''
git describe --tags --always > console_backend/src/version.txt
'''

[tasks.install-backend]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pip install -e ./console_backend
'''

[tasks.prod-install-backend]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV --no-capture-output --live-stream python -m pip install ./console_backend --upgrade --force ./console_backend -v
'''

[tasks.prod-freeze-no-copy]
dependencies = ["copy-capnp", "generate-resources", "prod-install-backend"]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV fbs freeze
'''

[tasks.copy-console-backend-to-fbs.windows]
script_runner = "powershell"
script_extension = "ps1"
script = '''
xcopy /E /Y /I .\console_backend\console_backend\server.cp38-win_amd64.pyd .\target\swift_navigation_console\console_backend\
'''

[tasks.copy-console-backend-to-fbs]
script_runner = "@shell"
script = '''
mkdir -p target/swift_navigation_console/console_backend && cp -r console_backend/console_backend/* target/swift_navigation_console/console_backend/.
'''

[tasks.prod-freeze]
dependencies = [
  "store-version",
  "prod-freeze-no-copy",
  "remove-negligibles",
  "copy-console-backend-to-fbs",
]

[tasks.prod-installer]
dependencies = ["prod-freeze"]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV fbs installer
'''

[tasks.create-remove-negligibles-file]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV python utils/get_fbs_remove_list.py
'''

[tasks.remove-negligibles.linux]
dependencies = []
script = '''
bash src/main/fbs/linux-remove-negligibles.sh
'''

[tasks.remove-negligibles.windows]
dependencies = []
script = '''
bash src/main/fbs/windows-remove-negligibles.sh
'''

[tasks.prod-nuitka-build.linux]
dependencies = ["copy-capnp", "store-version", "generate-resources"]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pip install --force ./console_backend
conda run -n $CONDA_ENV bash src/main/nuitka/linux.sh
'''

[tasks.prod-nuitka-build.mac]
dependencies = ["copy-capnp", "store-version", "generate-resources"]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pip install --force ./console_backend
conda run -n $CONDA_ENV bash src/main/nuitka/mac.sh
'''

[tasks.create-nuitka-script]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV python utils/create_nuitka_script.py
'''

[tasks.prod-installer.mac]
dependencies = ["prod-nuitka-build"]
script_runner = "@shell"
script = '''
mkdir -p main.app/Contents/MacOS main.app/Contents/Resources
cp -r main.dist/* main.app/Contents/MacOS/
iconutil --convert icns src/main/icons/Mac.iconset
mv src/main/icons/Mac.icns main.app/Contents/Resources/SwiftNavConsole.icns
conda run -n $CONDA_ENV python src/build/generate-mac-info-plist.py
hdiutil create -volname SwiftNavConsole -srcfolder main.app -ov -format UDZO 'swift_navigation_console.dmg' || (echo 'Failed to create Mac dmg. Retrying in 10s...' && sleep 10 && hdiutil create -volname SwiftNavConsole -srcfolder main.app -ov -format UDZO 'swift_navigation_console.dmg' )
'''

[tasks.qml-format]
env = { QT_APP = { script = [
  "conda run -n $CONDA_ENV python utils/echo-qt-dir.py",
] } }
script_runner = "@shell"
script = '''
${QT_APP}/Qt/bin/qmlformat -i $QML_FILES
'''

[tasks.qml-lint]
env = { QT_APP = { script = [
  "conda run -n $CONDA_ENV python utils/echo-qt-dir.py",
] } }
script_runner = "@shell"
script = '''
${QT_APP}/Qt/bin/qmllint -I ${QT_APP}/../PySide2/Qt/qml/ -I resources/ $QML_FILES
'''

[tasks.qml-format-check]
dependencies = ["qml-format"]
run_task = "check-git-diff"

[tasks.rust-format]
dependencies = ["copy-capnp"]
command = "cargo"
args = ["fmt", "--all"]

[tasks.rust-format-check]
dependencies = ["copy-capnp"]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.rust-lint]
dependencies = ["store-version", "copy-capnp"]
command = "cargo"
args = ["clippy", "--all-targets", "--", "--deny", "warnings"]

[tasks.rust-tests]
dependencies = ["store-version", "copy-capnp"]
command = "cargo"
cwd = "console_backend"
args = ["test", "--features", "tests", "--", "--nocapture"]

[tasks.rust-type-check]
dependencies = ["store-version", "copy-capnp"]
command = "cargo"
args = ["check"]

[tasks.python-type-check]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV mypy $PYTHON_FILES
'''

[tasks.python-format-check]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV black --check --diff $PYTHON_FILES
'''

[tasks.python-format-all]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV black $PYTHON_FILES
'''

[tasks.python-format]
alias = "python-format-all"

[tasks.python-lint]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pylint --output-format=parseable $PYTHON_FILES
'''

[tasks.format-toml-check]
# Note format-toml task is defined by cargo-make to use crate taplo-cli, but the version is
# unspecified.  Task cargo-make-deps-update keeps the dev version in sync with CI.
# https://github.com/sagiegurari/cargo-make/issues/571
dependencies = ["cargo-make-deps-update", "format-toml"]
run_task = "check-git-diff"

[tasks.format-all]
dependencies = [
  "python-format-all",
  "qml-format",
  "rust-format",
  "newline-format",
  "format-toml",
]

[tasks.format]
alias = "format-all"

[tasks.format-check]
dependencies = ["python-format-check", "rust-format-check", "newline-check"]
run_task = "check-git-diff"

[tasks.lint]
dependencies = ["qml-lint", "python-lint", "rust-lint", "format-check"]

[tasks.types]
dependencies = ["python-type-check", "rust-type-check"]

[tasks.check-all]
dependencies = [
  "cargo-make-deps-update",
  "poetry-export",
  "pip-install-dev",
  "generate-common-constants-rs",
  "extract-piksi-constants-rs",
  "format",
  "lint",
  "types",
]
run_task = "check-git-diff"

[tasks.tests]
dependencies = ["rust-tests"]

[tasks.backend-cpu-bench]
dependencies = ["copy-capnp", "generate-resources"]
command = "cargo"
args = ["bench", "--all-features", "--", "--verbose", "--noplot"]

[tasks.backend-cpu-bench-validate]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV python utils/bench_runner.py --backend_cpu
'''

[tasks.backend-mem-bench]
dependencies = ["copy-capnp", "generate-resources"]
command = "cargo"
args = [
  "test",
  "test_run_process_messages",
  "--manifest-path=console_backend/Cargo.toml",
  "--features",
  "benches",
  "--",
  "--nocapture",
]

[tasks.backend-benches]
dependencies = [
  "store-version",
  "backend-cpu-bench",
  "backend-cpu-bench-validate",
  "backend-mem-bench",
]

[tasks.disk-usage-bench]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV python utils/bench_runner.py --disk_usage
'''

[tasks.frontend-cpu-bench.linux]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_cpu --executable=${PWD}/../../target/swift_navigation_console/swift_navigation_console
'''

[tasks.frontend-cpu-bench.windows]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_cpu --executable=${PWD}/target/swift_navigation_console/swift_navigation_console.exe
'''

[tasks.frontend-cpu-bench.mac]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_cpu --executable=${PWD}/main.dist/main
'''

[tasks.frontend-mem-bench.linux]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_mem --executable=${PWD}/target/swift_navigation_console/swift_navigation_console
'''

[tasks.frontend-mem-bench.windows]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_mem --executable=${PWD}/target/swift_navigation_console/swift_navigation_console.exe
'''

[tasks.frontend-mem-bench.mac]
script_runner = "@shell"
script = '''
echo 'This is only used to validate locally.'
cd console_backend/tests && python ../../utils/bench_runner.py --frontend_mem --executable=${PWD}/main.dist/main
'''

[tasks.newline-terminator]
private = true
script_runner = "python"
script_extension = "py"
script = '''
import os
import sys
import subprocess
def raises_exc(func):
    try: func()
    except: return True
    return False
dry_run = os.environ.get("NLT_DRY_RUN", "") == "1"
open_append = lambda fn: open(fn, "ta")
open_read = lambda fn: open(fn, "rb")
seek_end = lambda fp: (fp.seek(-1, 2), fp)[-1]
has_newline = lambda fn: seek_end(open_read(fn)).read(1) == b"\n"
append_newline = lambda fn: (open_append(fn).write("\n") if not dry_run else None, fn)[-1]
try_open_text = lambda fn: lambda: (open(fn, "ta"), open(fn, "tr").read(4096))
valid_file = lambda fn: os.path.getsize(fn) > 0 and not raises_exc(try_open_text(fn))
no_trailing_lf = lambda fn: valid_file(fn) and not has_newline(fn)
all_files = subprocess.check_output(["git", "ls-files"]).decode('utf8').splitlines()
no_newline = list(map(append_newline, filter(no_trailing_lf, all_files)))
footer = "*********************************************\n"
err = "ERROR: " if dry_run else "Fixing "
header = footer + "*** " + err + "files missing trailing newline ***\n" + footer
sys.stderr.write(header + str.join("\n", no_newline) + "\n" + footer) \
  if no_newline else None
sys.exit(int(len(no_newline) > 0) if dry_run else 0)
'''

[tasks.newline-check]
env = { NLT_DRY_RUN = "1" }
run_task = "newline-terminator"

[tasks.newline-format]
run_task = "newline-terminator"

[tasks.check-git-diff]
script_runner = "@shell"
command = "git"
args = ["diff", "--exit-code"]
