[env]
PYTHON_FILES = { script = ["python utils/glob_python_files.py"] }
CONDA_ENV = "console_pp"

[config]
default_to_workspace = false

[tasks.generate-resources]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pyside2-rcc resources/console_resources.qrc -o src/main/python/console_resources.py
'''

[tasks.copy-capnp]
script_runner = "@shell"
script = '''
cp src/main/resources/base/console_backend.capnp console_backend/console_backend.capnp
'''

[tasks.run]
dependencies = ["copy-capnp", "generate-resources"]
script = '''
conda run -n $CONDA_ENV pip install -e ./console_backend
conda run -n $CONDA_ENV fbs run
'''

[tasks.prod-run]
dependencies = ["copy-capnp", "generate-resources"]
script = '''
conda run -n $CONDA_ENV pip install --force ./console_backend
conda run -n $CONDA_ENV fbs run
'''

[tasks.prod-freeze]
dependencies = ["copy-capnp", "generate-resources"]
script = '''
conda run -n $CONDA_ENV pip install --force ./console_backend
conda run -n $CONDA_ENV fbs freeze
'''

[tasks.prod-installer]
dependencies = ["prod-freeze", "remove-negligibles"]
script = '''
conda run -n $CONDA_ENV fbs installer
'''

[tasks.create-remove-negligibles-file]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV python utils/get_fbs_remove_list.py
'''

[tasks.remove-negligibles.linux]
dependencies = []
script = '''
bash src/main/fbs/linux-remove-negligibles.sh
'''

[tasks.remove-negligibles.windows]
dependencies = []
script = '''
bash src/main/fbs/windows-remove-negligibles.sh
'''

[tasks.prod-nuitka-build.linux]
dependencies = ["copy-capnp", "generate-resources"]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pip install --force ./console_backend
conda run -n $CONDA_ENV bash src/main/nuitka/linux.sh
'''

[tasks.prod-nuitka-build.mac]
dependencies = ["copy-capnp", "generate-resources"]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pip install --force ./console_backend
conda run -n $CONDA_ENV bash src/main/nuitka/mac.sh
'''

[tasks.create-nuitka-script]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV python utils/create_nuitka_script.py
'''

[tasks.prod-installer.mac]
dependencies = ["prod-nuitka-build"]
script_runner = "@shell"
script = '''
mkdir -p main.app/Contents/MacOS
cp -r main.dist/* main.app/Contents/MacOS/.
hdiutil create -volname SwiftNavConsole -srcfolder main.app -ov -format UDZO 'Swift Navigation Console.dmg'
'''

[tasks.rust-format]
dependencies = ["copy-capnp"]
command = "cargo"
args    = ["fmt", "--all"]

[tasks.rust-format-check]
dependencies = ["copy-capnp"]
command = "cargo"
args    = ["fmt", "--", "--check"]

[tasks.rust-lint]
dependencies = ["copy-capnp"]
command = "cargo"
args    = ["clippy", "--all-targets", "--", "--deny", "warnings"]

[tasks.rust-tests]
dependencies = ["copy-capnp"]
command = "cargo"
args    = ["test", "--", "--nocapture"]

[tasks.rust-type-check]
dependencies = ["copy-capnp"]
command = "cargo"
args    = ["check"]

[tasks.python-type-check]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV mypy $PYTHON_FILES
'''

[tasks.python-format-check]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV black --line-length=120 --check --diff $PYTHON_FILES
'''

[tasks.python-format-all]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV black --line-length=120 $PYTHON_FILES
'''

[tasks.python-format]
alias="python-format-all"

[tasks.python-lint]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV pylint --output-format=parseable $PYTHON_FILES
'''

[tasks.format-all]
dependencies = ["python-format-all", "rust-format"]

[tasks.format]
alias = "format-all"

[tasks.format-check]
dependencies = ["python-format-check", "rust-format-check"]

[tasks.lint]
dependencies = ["python-lint", "rust-lint"]

[tasks.types]
dependencies = ["python-type-check", "rust-type-check"]

[tasks.tests]
dependencies = ["rust-tests"]

[tasks.bench-rust]
dependencies = ["copy-capnp", "generate-resources"]
command = "cargo"
args    = ["bench", "--all-features", "--", "--verbose", "--noplot"]

[tasks.bench-rust-validate]
script_runner = "@shell"
script = '''
conda run -n $CONDA_ENV python console_backend/benches/benchmarks.py
'''

[tasks.benches]
dependencies = ["bench-rust", "bench-rust-validate"]
