[tool.poetry]
name = "swiftnav_console"
version = "0.0.0"
description = ""
authors = ["Swift Navigation <dev@swiftnav.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
PySide2 = "^5.15.2"
fbs = { git = "https://github.com/silverjam/fbs.git" }
pycapnp = "^1.1.0"
cbor2 = "^5.4.1"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
jedi = "^0.18.0"
mypy = "^0.910"
pylint = "^2.9.3"
pytest = "^6.2.4"
setuptools-rust = "^0.12.1"
nuitka = "<=0.6.12.4"
psutil = "5.8.0"
qt5-applications = [{ version = "^5.15.2" }]
py2many = ">=0.3"
types-requests = "^2.25.0"

[build-system]
requires = [
  "poetry-core>=1.0.0",
  "setuptools>=41.0.0",
  "wheel",
  "setuptools_rust>=0.10.2",
]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
