[tool.poetry]
name = "swiftnav_console"
version = "0.0.0"
description = ""
authors = ["Swift Navigation <dev@swiftnav.com>"]

[tool.poetry.dependencies]
python = "^3.7"
PySide2 = "5.12.2"
sbp = "^3.4.5"
numpy = "^1.19.5"
fbs = {git = "https://github.com/silverjam/fbs.git"}

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
jedi = "^0.18.0"
mypy = "^0.790"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
