[tool.poetry]
name = "swiftnav_console"
version = "0.0.0"
description = ""
authors = ["Swift Navigation <dev@swiftnav.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
PySide2 = "^5.15.2"
pycapnp = { path = "pycapnp.tgz" }
fbs = {git = "https://github.com/silverjam/fbs.git"}

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
jedi = "^0.18.0"
mypy = "^0.790"
setuptools-rust = "^0.11.6"
Nuitka = "^0.6.11"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=41.0.0", "wheel", "setuptools_rust>=0.10.2"]
build-backend = "poetry.core.masonry.api"
