[package]
authors = ["Swift Navigation <dev@swift-nav.com>"]
name = "console"
version = "0.1.0"
description = "Starts the console with the correct python installation"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.15", features = ["auto-initialize"] }

[[bin]]
name = "console"
path = "src/main.rs"
bench = false

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = ">=0.24", features = [
  "Win32_System_Console",
  "Win32_Foundation",
] }

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "0.1"
