[package]
authors = ["Swift Navigation <dev@swift-nav.com>"]
name = "console-backend"
version = "0.1.0"
description = "A Python wrapper for the Rust console backend"
edition = "2018"

[dependencies]
log = "0.4.14"
async_logger_log = "0.2.0"
async_logger = "0.3.3"
strum = "0.23"
strum_macros = "0.23"
lazy_static = "1.4.0"
capnp = "0.14"
chrono = { version = "0.4", features = ["serde"] }
csv = "1"
paste = "1"
pyo3 = { version = "0.15", features = [
  "extension-module",
  "macros",
], default-features = false, optional = true }
serde = { version = "1.0.134", features = ["derive"] }
tempfile = "3.3.0"
ordered-float = "2.10"
ndarray = "0.15.4"
glob = "0.3.0"
criterion = "0.3.4"
sysinfo = "0.23.0"
serialport = { git = "https://github.com/swift-nav/serialport-rs.git", default-features = false }
directories = "4"
anyhow = { version = "1", features = ["backtrace"] }
serde_yaml = "0.8.23"
clap = { version = "3.0.10", features = ["derive"] }
indexmap = { version = "1.8.0", features = ["serde"] }
serde_json = { version = "1" }
crossbeam = "0.8"
rand = "0.8.3"
serde-pickle = { version = "1.1.0", optional = true }
parking_lot = "0.11.1"
regex = { version = "1.5.4" }
rust-ini = "0.17.0"
sbp = { version = "4.1.1", features = ["json", "link", "swiftnav"] }
sbp-settings = "0.6.0"
env_logger = { version = "0.9", optional = true }
mimalloc = { version = "0.1", default-features = false }
curl = { version = "0.4", features = ["ssl", "static-curl"] }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
serialport = { git = "https://github.com/swift-nav/serialport-rs.git" }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = ">=0.24", features = [
  "Win32_System_Console",
  "Win32_Foundation",
] }

[dev-dependencies]
logtest = "2.0.0"
serial_test = "0.5.1"

[build-dependencies]
capnpc = "0.14"

[lib]
name = "console_backend"
crate-type = ["cdylib", "lib"]
bench = false

[[bench]]
name = "cpu_benches"
harness = false

[[bin]]
name = "fileio"
path = "src/bin/fileio.rs"
bench = false
required-features = ["env_logger"]

[[bin]]
name = "fft_monitor"
path = "src/bin/fft_monitor.rs"
bench = false
required-features = ["fft"]

[[bin]]
name = "headless-console"
path = "src/bin/headless-console.rs"
bench = false

[features]
default = ["pyo3"]
benches = []
tests = []
fft = ["serde-pickle"]
