[package]
authors = ["Swift Navigation <dev@swift-nav.com>"]
name = "console-backend"
version = "0.1.0"
description = "A Python wrapper for the Rust console backend"
edition = "2018"

[dependencies]
strum = "0.20"
strum_macros = "0.20"
lazy_static = "1.4.0"
capnp = "0.14"
chrono = { version = "0.4", features = ["serde"] }
csv = "1"
paste = "1"
pyo3 = { version = "0.13", features = ["extension-module"] }
sbp = { git = "https://github.com/swift-nav/libsbp.git", rev = "0563350bb387e4a966a2b558adb7b05b2baf005f" }
serde = { version = "1.0.123", features = ["derive"] }
tempfile = "3.2.0"
ordered-float = "2.0"
ndarray = "0.14.0"
glob = "0.3.0"
criterion = "0.3.4"
sysinfo = "0.16.4"
serialport = { version = "4.0.1", default-features = false }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
serialport = "4.0.1"

[[bench]]
name = "cpu_benches"
harness = false


[build-dependencies]
capnpc = "0.14"

[lib]
name = "console_backend"
crate-type = ["cdylib", "lib"]
bench = false

[features]
default = []
benches = []
