[package]
authors = ["Swift Navigation <dev@swift-nav.com>"]
name = "console-backend"
version = "0.1.0"
description = "A Python wrapper for the Rust console backend"
edition = "2018"

[dependencies]
capnp = "0.14"
pyo3 = { version = "0.13", features = ["extension-module"] }
sbp = { git = "https://github.com/swift-nav/libsbp.git", rev = "bee5001068bc36c4a3385548dbd5478d7c95fcee" }
ordered-float = "2.0"
ndarray = "0.14.0"
glob = "0.3.0"
criterion = "0.3.4"
sysinfo = "0.16.4"

[[bench]]
name = "cpu_benches"
harness = false


[build-dependencies]
capnpc = "0.14"

[lib]
name = "console_backend"
crate-type = ["cdylib", "lib"]
bench = false

[features]
default = []
benches = []
