[package]
authors = ["Swift Navigation <dev@swift-nav.com>"]
name = "console-backend"
version = "0.1.0"
description = "A Python wrapper for the Rust console backend"
edition = "2018"

[dependencies]
log = "0.4.14"
async_logger_log = "0.2.0"
async_logger = "0.3.3"
strum = "0.20"
strum_macros = "0.20"
lazy_static = "1.4.0"
capnp = "0.14"
chrono = { version = "0.4", features = ["serde"] }
csv = "1"
paste = "1"
pyo3 = { version = "0.13", features = ["extension-module"] }
sbp = { git = "https://github.com/swift-nav/libsbp.git", rev = "629974666b1aa5fdab9fdbd517e180a2aee3809b", features = ["swiftnav-rs"]}
serde = { version = "1.0.123", features = ["derive"] }
tempfile = "3.2.0"
ordered-float = "2.0"
ndarray = "0.14.0"
glob = "0.3.0"
criterion = "0.3.4"
sysinfo = "0.16.4"
serialport = { version = "4.0.1", default-features = false }
directories = "3"
once_cell = "1"
xshell = "0.1"
anyhow = { version = "1", features = ["backtrace"] }
serde_yaml = "0.8.17"
clap = "3.0.0-beta.2"

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
serialport = "4.0.1"

[[bench]]
name = "cpu_benches"
harness = false

[dev-dependencies]
logtest = "2.0.0"

[build-dependencies]
capnpc = "0.14"

[lib]
name = "console_backend"
crate-type = ["cdylib", "lib"]
bench = false

[features]
default = []
benches = []
tests = []
