[package]
authors = ["Swift Navigation <dev@swift-nav.com>"]
name = "console-backend"
version = "0.1.0"
description = "A Python wrapper for the Rust console backend"
edition = "2018"

[dependencies]
log = "0.4.14"
async_logger_log = "0.2.0"
async_logger = "0.3.3"
strum = "0.20"
strum_macros = "0.20"
lazy_static = "1.4.0"
capnp = "0.14"
chrono = { version = "0.4", features = ["serde"] }
csv = "1"
paste = "1"
pyo3 = { version = "0.13", features = ["extension-module"], optional = true }
serde = { version = "1.0.123", features = ["derive"] }
tempfile = "3.2.0"
ordered-float = "2.0"
ndarray = "0.14.0"
glob = "0.3.0"
criterion = "0.3.4"
sysinfo = "0.16.4"
serialport = { version = "4.0.1", default-features = false }
directories = "3"
anyhow = { version = "1", features = ["backtrace"] }
serde_yaml = "0.8.17"
clap = "3.0.0-beta.2"
indexmap = { version = "1.6.2", features = ["serde"] }
serde_json = { version = "1" }
crossbeam = "0.8.1"
rand = "0.8.3"
slotmap = "1.0.3"
serde-pickle = { version = "0.6.2", optional = true }
parking_lot = "0.11.1"
minreq = { version = "2.4.2", features = ["https"] }
regex = { version = "1.5.4" }
semver = { version = "1" }
rust-ini = "0.17.0"
snap = { version = "1", optional = true }

[dependencies.sbp]
git = "https://github.com/swift-nav/libsbp.git"
rev = "0f35aacf110a9dbe0b832e5feb415933cd0c7f6e"
features = ["json", "swiftnav-rs", "link"]

[dependencies.libsettings]
git = "https://github.com/swift-nav/libsettings.git"
rev = "79c5a023dab189532de45fb806d4c295911caa0e"

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
serialport = "4.0.1"

[[bench]]
name = "cpu_benches"
harness = false

[dev-dependencies]
logtest = "2.0.0"
serial_test = "0.5.1"

[build-dependencies]
capnpc = "0.14"

[lib]
name = "console_backend"
crate-type = ["cdylib", "lib"]
bench = false

[[bin]]
name = "fileio"
path = "src/bin/fileio.rs"
bench = false

[[bin]]
name = "fft_monitor"
path = "src/bin/fft_monitor.rs"
bench = false
required-features = ["fft"]

[[bin]]
name = "headless-console"
path = "src/bin/headless-console.rs"
bench = false
required-features = ["headless-console"]

[features]
default = ["pyo3"]
benches = []
tests = []
fft = ["serde-pickle"]
headless-console = ["snap"]
