name: Sync draw.io diagrams
on:
  push:
    branches:
      - "steve/draw-sync"
    paths:
      - "docs/imgs/*.drawio"
      - .github/workflows/drawio-sync.yaml
jobs:
  drawio-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-strict: false

      - name: Export drawio diagrams as png files
        uses: rlespinasse/drawio-export-action@v1.x
        with:
          format: png
          remove-page-suffix: true
          transparent: true

      - name: Get author and committer info from HEAD commit
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: sync draw.io exported files
          commit_user_name: "${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          commit_user_email: "${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          commit_author: "${{ env.GIT_COMMIT_AUTHOR }}"
